<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\Application\BankSystemApi.Application.Abstractions\BankSystemApi.Application.Abstractions.csproj" />
    <ProjectReference Include="..\..\Presentation\BankSystemApi.Presentation.Grpc\BankSystemApi.Presentation.Grpc.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentMigrator" />
    <PackageReference Include="FluentMigrator.Runner.Postgres" />
    <PackageReference Include="Itmo.Dev.Platform.Persistence.Postgres" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="IntegrationalTests"/>
  </ItemGroup>
</Project>
