<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoBogus" />
        <PackageReference Include="coverlet.collector" />
        <PackageReference Include="FluentAssertions" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Moq" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\service\Application\BankSystemApi.Application.Abstractions\BankSystemApi.Application.Abstractions.csproj" />
      <ProjectReference Include="..\..\src\service\Application\BankSystemApi.Application\BankSystemApi.Application.csproj" />
    </ItemGroup>

</Project>