<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <OutputType>Library</OutputType>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Application\BankSystemApi.Gateway.Application.Contracts\BankSystemApi.Gateway.Application.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
      <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
      <PackageReference Include="Scalar.AspNetCore" />
      <PackageReference Include="Swashbuckle.AspNetCore" />
    </ItemGroup>

</Project>
