<Project Sdk="Aspire.AppHost.Sdk/13.2.2">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <UserSecretsId>7e936314-a2ef-41fe-b0f2-97e7a7af2ab0</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.Keycloak" />
        <PackageReference Include="Aspire.Hosting.PostgreSQL" />
        <PackageReference Include="Aspire.Hosting.Redis" />
        <PackageReference Include="DotNetEnv" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\gateway\BankSystemApi.Gateway\BankSystemApi.Gateway.csproj" />
      <ProjectReference Include="..\..\service\BankSystemApi\BankSystemApi.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="appsettings.Development.json">
        <DependentUpon>appsettings.json</DependentUpon>
      </None>
    </ItemGroup>

</Project>
