syntax = "proto3";
import "models.proto";

package bsa.sharp_backend;
option csharp_namespace = "Bsa.CsharpBackend.Grpc";

import "google/type/money.proto";

service AccountService {
  rpc Create(CreateAccountRequest) returns (CreateAccountResponse);

  rpc Deposit(DepositRequest) returns (DepositResponse);

  rpc Withdraw(WithdrawRequest) returns (WithdrawResponse);

  rpc GetBalance(GetBalanceRequest) returns (GetBalanceResponse);
}

message CreateAccountRequest {
  string id = 1;
  string account_number = 2;
  string password = 3;
}

message CreateAccountResponse {
  Account account = 1;
}

message DepositRequest {
  string id = 1;
  google.type.Money amount = 2;
}

message DepositResponse {
  Account account = 1;
}

message WithdrawRequest {
  string id = 1;
  google.type.Money amount = 2;
}

message WithdrawResponse {
  Account account = 1;
}

message GetBalanceRequest {
  string id = 1;
}

message GetBalanceResponse {
  google.type.Money balance = 1;
}