<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\Application\Bsa.Gateway.Application\Bsa.Gateway.Application.csproj" />
    <ProjectReference Include="..\Infrastructure\Bsa.Gateway.Infrastructure.BankService\Bsa.Gateway.Infrastructure.BankService.csproj" />
    <ProjectReference Include="..\Presentation\Bsa.Gateway.Presentation.Http\Bsa.Gateway.Presentation.Http.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>
</Project>
