<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
      <PackageReference Include="FluentMigrator" />
      <PackageReference Include="FluentMigrator.Runner.Postgres" />
      <PackageReference Include="Microsoft.Extensions.Configuration" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
      <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
      <PackageReference Include="Npgsql" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Application\Bsa.Application.Abstractions\Bsa.Application.Abstractions.csproj" />
    </ItemGroup>

</Project>
