syntax = "proto3";
import "models.proto";

package bank_system_api;
option csharp_namespace = "BankSystemApi.Grpc";

import "google/protobuf/wrappers.proto";


service HistoryOperationService {
  rpc Get(GetHistoryOperationRequest) returns (GetHistoryOperationResponse);
}

message GetHistoryOperationRequest {
  string user_id = 1;
  string account_id = 2;
  Pagination pagination = 3;
}

message GetHistoryOperationResponse {
  repeated HistoryOperation history = 1;
  google.protobuf.StringValue page_token = 2;
}
