syntax = "proto3";
import "models.proto";

package bsa.sharp_backend;
option csharp_namespace = "Bsa.CsharpBackend.Grpc";

import "google/protobuf/wrappers.proto";


service HistoryOperationService {
  rpc GetHistoryOperation(GetHistoryOperationRequest) returns (GetHistoryOperationResponse);
}

message GetHistoryOperationRequest {
  string id = 1;
  Pagination pagination = 2;
}

message GetHistoryOperationResponse {
  repeated HistoryOperation history = 1;
  google.protobuf.StringValue page_token = 2;
}
