<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <NoWarn>$(NoWarn);CA1506</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\aspire\Bank-System-Api.ServiceDefaults\Bank-System-Api.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Application\BankSystemApi.Application\BankSystemApi.Application.csproj" />
    <ProjectReference Include="..\Infrastructure\BankSystemApi.Infrastructure.Kafka\BankSystemApi.Infrastructure.Kafka.csproj" />
    <ProjectReference Include="..\Infrastructure\BankSystemApi.Infrastructure.Persistence\BankSystemApi.Infrastructure.Persistence.csproj" />
    <ProjectReference Include="..\Presentation\BankSystemApi.Presentation.Kafka\BankSystemApi.Presentation.Kafka.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="appsettings.Development.json">
      <DependentUpon>appsettings.json</DependentUpon>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Itmo.Dev.Platform.MessagePersistence.Postgres" />
    <PackageReference Include="Npgsql.OpenTelemetry" />
    <PackageReference Include="Prometheus.Client.AspNetCore" />
    <PackageReference Include="Prometheus.Client.DependencyInjection" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Enrichers.ActivityTags" />
    <PackageReference Include="Serilog.Enrichers.Span" />
    <PackageReference Include="Serilog.Sinks.OpenTelemetry" />
  </ItemGroup>
</Project>
