<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
      <NoWarn>$(NoWarn);CA1506</NoWarn>
    </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Domain\Bsa.Domain\Bsa.Domain.csproj" />
    <ProjectReference Include="..\Bsa.Application.Abstractions\Bsa.Application.Abstractions.csproj" />
    <ProjectReference Include="..\Bsa.Application.Contracts\Bsa.Application.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Itmo.Dev.Platform.Common" />
    <PackageReference Include="Itmo.Dev.Platform.Persistence.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
  </ItemGroup>
</Project>
