<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <Protobuf Include="protos/**/*.proto" ProtoRoot="protos" GrpcServices="Client"/>
        <Protobuf Remove="protos/google/**/*.proto" />
    </ItemGroup>
    
  <ItemGroup>
    <PackageReference Include="Google.Api.CommonProtos" />
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Grpc.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="SourceKit.Generators.Grpc" />
  </ItemGroup>
    
  <ItemGroup>
    <ProjectReference Include="..\..\Application\Bsa.Gateway.Application.Abstractions\Bsa.Gateway.Application.Abstractions.csproj" />
  </ItemGroup>
</Project>
