syntax = "proto3";
import "models.proto";

package bank_system_api;
option csharp_namespace = "BankSystemApi.Grpc";

import "google/protobuf/wrappers.proto";
import "google/type/money.proto";

service InvoiceService {
  rpc CreateInvoice(CreateInvoiceRequest) returns (CreateInvoiceResponse);

  rpc PayInvoice(PayInvoiceRequest) returns (PayInvoiceResponse);

  rpc RevokeInvoice(RevokeInvoiceRequest) returns (RevokeInvoiceResponse);

  rpc GetInvoice(GetInvoicesRequest) returns (GetInvoicesResponse);
}

message CreateInvoiceRequest {
  string user_id = 1;
  string sender_account_id = 2;
  string receiver_account_id = 3;
  google.type.Money amount = 4;
}

message CreateInvoiceResponse {
  Invoice invoice = 1;
}

message PayInvoiceRequest {
  string user_id = 1;
  int64 invoice_id = 2;
}

message PayInvoiceResponse {
  Invoice invoice = 1;
}

message RevokeInvoiceRequest {
  string user_id = 1;
  int64 invoice_id = 2;
}

message RevokeInvoiceResponse {
  Invoice invoice = 1;
}

message GetInvoicesRequest {
  string user_id = 1;
  repeated string foreign_account_ids = 2;
  repeated InvoiceStatus statuses = 3;
  InvoiceType invoice_type = 4;
  Pagination pagination = 5;
}

message GetInvoicesResponse {
  repeated Invoice invoices = 1;
  google.protobuf.StringValue page_token = 2;
}