<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <OutputType>Library</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <Protobuf Include="protos/**/*.proto" ProtoRoot="protos" GrpcServices="Server" />
        <Protobuf Remove="protos/google/**/*.proto" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Google.Api.CommonProtos" />
        <PackageReference Include="Google.Protobuf" />
        <PackageReference Include="Grpc.AspNetCore"/>
        <PackageReference Include="Grpc.AspNetCore.Server.Reflection"/>
        <PackageReference Include="Grpc.Tools">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="SourceKit.Generators.Grpc" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Application\Bsa.Application.Contracts\Bsa.Application.Contracts.csproj" />
    </ItemGroup>

</Project>
